// ... existing code ...
                        selectedModel: chatProvider.selectedModel,
                        availableModels: chatProvider.availableModels,
                      );
// ... existing code ...
