name: otto
description: A beautiful and modern chat interface powered by Otto.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  google_fonts: ^6.2.1
  uuid: ^4.3.3
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.6+2
  markdown: ^7.2.1
  flutter_highlight:
    path: ../highlight.dart/flutter_highlight
  url_launcher: ^6.2.4
  flutter_launcher_icons: ^0.14.3
  simple_animations: ^5.1.0
  flutter_animate: ^4.5.0
  flutter_chat_types: ^3.6.2
  gpt_markdown:
    path: ../gpt_markdown # Ensure gpt_markdown also uses local path

  # E2EE Dependencies
  encrypt: ^5.0.3 # For AES/RSA encryption
  flutter_secure_storage: ^9.2.2 # For secure key storage
  pointycastle: ^3.9.1 # For RSA key generation and operations
  rsa_pkcs: ^2.1.0 # For PEM encoding/decoding compatible with pointycastle
  qr_flutter: ^4.1.0 # For generating QR codes
  mobile_scanner: ^5.1.1 # For scanning QR codes
  asn1lib: ^1.5.0 # Add ASN.1 library for proper key encoding
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../macOS Icon Design Template (2).png"
  macos:
    generate: true
    image_path: "temp_icons/padded_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  # Fonts are now being loaded from Google Fonts
  # No need to maintain local font files
